name: C++ doctest (Windows)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up MSVC (cl.exe)
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build tests
        shell: cmd
        run: |
          REM Compile main.cpp in TEST MODE
          REM /MDd = Debug runtime (REQUIRED for doctest)
          REM /D_DEBUG enables doctest main
          REM /EHsc standard C++ exceptions
          REM /std:c++17 C++17 standard

          cl /nologo /EHsc /std:c++17 /MDd /D_DEBUG main.cpp /Fe:tests.exe


      - name: Run tests
        shell: cmd
        run: |
          tests.exe
